name: black

on:
  - push
  - pull_request
permissions: {}

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: psf/black@stable
